name: Build
on:
  pull_request:
  push:
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: erlef/setup-beam@v1.15.0
        with:
          otp-version: 24.0
          elixir-version: 1.12.1
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            priv/plts
            deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}-${{ matrix.elixir }}-${{ matrix.otp }}
      - run: mkdir -p priv/plts/
      - run: mix deps.get
      - run: MIX_ENV=test_dev mix format --check-formatted
      - run: MIX_ENV=test_dev mix credo

  test:
    runs-on: ubuntu-20.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      fail-fast: false
      matrix:
        otp: ['24.3', '25.2']
        elixir: ['1.12', '1.14']
        exclude:
          - elixir: '1.12'
            otp: '25.2'
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: erlef/setup-beam@v1.15.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            priv/plts
            deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}-${{ matrix.elixir }}-${{ matrix.otp }}
      - run: mkdir -p priv/plts/
      - run: mix deps.get
      - run: mix test
      - run: if [ "$SKIP_DIALYZER" != "true" ]; then mix dialyzer; fi
        env:
          SKIP_DIALYZER: ${{ matrix.skip_dialyzer }}
